name: client
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [main]
    paths:
      - 'packages/client/**'
      - .github/workflows/client.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/client/**'
      - .github/workflows/client.yml
      - pnpm-lock.yaml
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - uses: crazy-max/ghaction-setup-docker@v3
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter @fission-codes/client run lint
      - run: pnpm -r --filter @fission-codes/client run test
      - run: pnpm -r --filter @fission-codes/client exec depcheck
