name: homestar-wit
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [main]
    paths:
      - 'packages/homestar-wit/**'
      - .github/workflows/homestar-wit.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/homestar-wit/**'
      - .github/workflows/homestar-wit.yml
      - pnpm-lock.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter @fission-codes/homestar-wit run lint
      - run: pnpm -r --filter @fission-codes/homestar-wit run test
      - run: pnpm -r --filter @fission-codes/homestar-wit exec depcheck
