name: homestar
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [main]
    paths:
      - 'packages/homestar/**'
      - .github/workflows/homestar.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/homestar/**'
      - .github/workflows/homestar.yml
      - pnpm-lock.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter @fission-codes/homestar run lint
      - run: pnpm -r --filter @fission-codes/homestar run test
      - run: pnpm -r --filter @fission-codes/homestar exec depcheck
