name: Release

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # needs to be personal token so release PRs can run workflows
          token: ${{ secrets.GH_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          release-type: node
  npm:
    needs: release
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/eslint-config') ||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/homestar')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm -r publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  docs:
    needs: release
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/eslint-config')||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/homestar')
    uses: ./.github/workflows/reusable-docs.yml
